<?php

namespace My\FrontendBundle\Repository;

/**
 * NAMESRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NAMESRepository extends \Doctrine\ORM\EntityRepository
{
}
